### PR TITLE
Added help for Mac User at  need sudo

### PR DESCRIPTION
**Pull request by Flamintus**
Little precision in Readme to avoid this error, use sudo on macos

Capture d’écran 2022-03-30 à 18 19 00

### CODE REVIEW

**Comment by joelemanoel** [comment]
+1

**Comment by mifi** [comment]
using npm with sudo is not an advised thing to do. I think it's not a good thing to suggest. 

I think maybe instead we could recommend `brew install node`, what do you think?

**Comment by Flamintus** [comment]
On my side, I just found sudo as workaround, thank you for the advise. I've just tested with  'brew install node' and it's work like a charm ! So  yes for me

**Comment by Flamintus** [comment]
Are you modifying on your side or do you went a new PR ?

**Comment by mifi** [comment]
i added to readme. thanks

**Pull request closed without merging**
