### PR TITLE
 #109 Added second login button to click

### PR DESCRIPTION
**Pull request by Luen**
#109 109

### CODE REVIEW

**Comment by mifi** [comment]
thanks for your PR. but I'm not sure how it would work. Did you test it?
`//button/div['Log In']` evaluates to `<div class="_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9p">Log in</div>`
and you cannot click on a `<div>`

**Comment by Luen** [comment]
Yes, I test it once and it worked for me. I can delete the cookie file and try again.

**Comment by Luen** [comment]
It worked this time as well but it didn't use the fallback method as it did in the first test.

**Comment by mifi** [comment]
Ah, I know what's the problem. the problem is that in your html `<div class="_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9p  _abak _abb8 _abbq _abb-"><button class="_acan _acap _acas" type="submit"><div class="_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9p">Log in</div></button></div>` the text is `Log in`. but the code checks for `Log In` (capital I). and apparently XPath is case sensitive. I will add a fix

**Comment by Luen** [comment]
Thank you

**Comment by Luen** [comment]
Got it again today.

Screenshot:
image


Code:
```
<form class="_ab3b" id="loginForm" method="post">
   <div class="_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9p  _abc2">
      <div class="_ab32">
         <div class="_aa5k">
            <label class="_aa48 _aa49"><span class="_aa4a">Phone number, username, or email</span><input aria-label="Phone number, username, or email" aria-required="true" autocapitalize="off" autocorrect="off" maxlength="75" name="username" type="text" class="_aa5o _aa4b _ac4d" value="username"></label>
            <div class="_aa5p"></div>
         </div>
      </div>
      <div class="_ab32">
         <div class="_aa5k">
            <label class="_aa48 _aa49"><span class="_aa4a">Password</span><input aria-label="Password" aria-required="true" autocapitalize="off" autocorrect="off" name="password" type="password" class="_aa5o _aa4b _ac4d" value="PhysiosharkMoorea"></label>
            <div class="_aa5p">
               <div class="_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9p  _abb0"><button class="_acan _acao _acat" type="button">Show</button></div>
            </div>
         </div>
      </div>
      <div class="_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9p  _abak _abb8 _abbq _abb-">
         <button class="_acan _acap _acas" type="submit">
            <div class="_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9p">Log in</div>
         </button>
      </div>
      <div class="_aahq _ab39">
         <div class="_aahr _ac3x"></div>
         <div class="_aahs">or</div>
         <div class="_aahr _ac3x"></div>
      </div>
      <div class="_ab8w  _ab94 _ab99 _ab9f _ab9m _ab9p  _abak _abb8 _abbq _abb-"><button class="_acan _acao _acas" type="button"><span class=" _a04s _ab36"></span><span class="_ab37">Log in with Facebook</span></button></div>
   </div>
   <a class="oajrlxb2 g5ia77u1 qu0x051f esr5mh6w e9989ue4 r7d6kgcz rq0escxv nhd2j8a9 nc684nl6 p7hjln8o kvgmc6g5 cxmmr5t8 oygrvhab hcukyx3x jb3vyjys rz4wbd8a qt6c0cv9 a8nywdso i1ao9s8h esuyzwwr f1sip0of lzcic4wl _ab2y _a6hd" href="/accounts/password/reset/?hl=en" role="link" tabindex="0">Forgot `password?</a>
</form>
```

**Pull request closed without merging**
