### PR TITLE
Add get all user ids that liked a post

### PR DESCRIPTION
**Pull request by joelemanoel**
PR based on #39

### CODE REVIEW

**Comment by joelemanoel** [comment]
@mifi I used the "content" because it could be a Reels or IGTV, would you like me to use the term "Post"? If you feel necessary, you can change the code.

**Comment by mifi** [comment]
Thanks for your PR! Looks good, but I took the liberty of rewriting it to avoid code duplication, so I made a common GraphQL query function. Would you like to verify that it still works?

Do you have some example cod that you use to test it? Maybe you can share it as a comment in this PR

**Comment by joelemanoel** [comment]
> Thanks for your PR! Looks good, but I took the liberty of rewriting it to avoid code duplication, so I made a common GraphQL query function. Would you like to verify that it still works?
> 
> Do you have some example cod that you use to test it? Maybe you can share it as a comment in this PR

Its work for me.

I use this:
`
const getUsersWhoLikedContent= await instauto.getUsersWhoLikedContent({ contentId: 'CX9Oz0uLwEv', maxPages: 10 });
console.log(getUsersWhoLikedContent);
`

**Comment by mifi** [comment]
thanks

**Pull request merged**
